packages:
  - 'packages/*'
  - 'example'

allowBuilds:
  electron: true
  esbuild: true
  lefthook: true

catalog:
  react: '19.2.8'
  react-dom: '19.2.8'
  '@types/node': '^24.13.3'
  '@types/react': '^19.2.14'
  rozenite: '^2.0.0'
  '@rozenite/metro': '^2.0.0'
  '@rozenite/plugin-bridge': '^2.0.0'
  '@rozenite/vite-plugin': '^2.0.0'
