name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          package_json_file: ./package.json
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check format
        run: pnpm format:check
      - name: Lint
        run: pnpm lint --format github
      - name: Check for unused exports and dependencies
        run: pnpm knip
      - name: Typecheck
        run: pnpm typecheck
