name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup
        uses: ./.github/actions/setup
      - name: Check format
        run: pnpm format:check
      - name: Check for unused exports and dependencies
        run: pnpm knip
      - name: Required checks
        uses: ./.github/actions/required-checks
